version: '3'

services:
  mongodb:
    image: mongo:5.0
    container_name: printtrack-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: printtrack
      MONGO_INITDB_ROOT_PASSWORD: printtrack123
      MONGO_INITDB_DATABASE: printtrack
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - printtrack-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: printtrack-backend
    restart: always
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://printtrack:printtrack123@mongodb:27017/printtrack?authSource=admin
      - JWT_SECRET=printtrack_jwt_secret_key_production
      - JWT_EXPIRE=30d
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - printtrack-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: printtrack-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - printtrack-network

networks:
  printtrack-network:
    driver: bridge

volumes:
  mongodb_data:
