version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: always
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - printtrack-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always
    networks:
      - printtrack-network

networks:
  printtrack-network:
    driver: bridge
